# Determines if plugin should run at all
enabled: true

# min time between reports seconds
reportcooldowntime: 500

reporttypes:
  playerreport:
    enabled: true
  bugreport:
    enabled: true
  otherreport:
    enabled: true

discordwebhook:
  enabled: true
  webhookURL: ""



